
name: card_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ^3.32.0

dependencies:
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  meta: ^1.16.0
  shared_preferences: ^2.5.3
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.6.0
  json_serializable: ^6.10.0
  mocktail: ^1.0.4
  test: ^1.26.2
  very_good_analysis: ^9.0.0